### PR TITLE
epic: use github api data

### PR DESCRIPTION
**Pull request by radek-novak**
1. [x] - check if old key `32af5...`was removed from devops@mycs.com
2. [x] - make repo public
3. [x] - rebuild
 
- [x] - fix tests?
image

### CODE REVIEW

**Comment by NicolasRitouet** [comment]
It's building, but unfortunately, the token is visible in the build log (cf https://circleci.com/gh/mycsHQ/reviewly/49)

**Comment by NicolasRitouet** [comment]
@radek-novak can we merge this?

**Comment by radek-novak** [comment]
I'll try to fix the tests, that's the only issue here

**Comment by radek-novak** [comment]
I'll look at the tests tomorrow

**Comment by radek-novak** [comment]
@NicolasRitouet we can merge this

**Pull request merged**
